version: "3"

services:
  app:
    build: .
    volumes:
      - "./:/opt/app"
    ports:
      - "8000:8000"
    command:
      - "uvicorn"
      - "ifconfig.app:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"

